### ISSUE TITLE
Extremely verbose style

### ISSUE THREAD

**Issue by StoneCypher** [ellowrath/ClangMan#16]
High line count means hard to read code.  Reducing line count is an enormous readability win, which in turn is each a maintainability and extensibility win.  Strive to find short, idiomatic ways to write things.

[By example](https://github.com/ellowrath/ClangMan/blob/dev/clangman.c#L219),

```c
static bool evaluate_victory() {
    if (strcmp(game.chosenWord, game.maskedWord) == 0) {
        return true;
    }
    else {
        return false;
    }
}
```

is

```c
static bool evaluate_victory() {
  return (strcmp(game.chosenWord, game.maskedWord) == 0);
}
```

**Comment by ellowrath** [comment]
😞 I shouldn't have to be told this one.

**Comment by StoneCypher** [comment]
Literally ***everyone*** has to be told this one (including me)

**Comment by StoneCypher** [comment]
The worst is looking at your own code from two years ago, when the thing that seemed neat isn't anymore, and you just want it to be normal god damnit
