### ISSUE TITLE
Default to pre-increment

### ISSUE THREAD

**Issue by StoneCypher** [ellowrath/ClangMan#19]
In [lines like this](https://github.com/ellowrath/ClangMan/blob/dev/clangman.c#L76), you write perfectly innocuous code like this:

```c
while (read_bytes) {
    if (p[i] == '\n') {
        ret++;
    }
```

Please make that `++ret` instead.

In this particular case it will make no difference whatsoever.  However, there are times at which preincrement is faster than postincrement, and times where it makes no difference.  Postincrement literally never wins, and therefore should only be used when its difference is germane to the operation being undertaken.

This is neckbeardy as shit and not a big deal; it's just a good habit to be in.

The issue is around `temporaries`.

In the stupid case, preincrement is significantly less work than postincrement, because 

* In preincrement
    * first you change the number, 
    * then you work with it
* In postincrement
    * first you copy the number to a temporary
    * then you increment the number
    * then you work with the temporary

Because incrementation nearly universally happens in loops or matrix operations, the creation, copying, management, and lifecycle destruction of the temporaries is potentially repeated hundreds of thousands of times, and may be very expensive in the aggregate.

In most cases, especially when dealing with primitives like ints and floats, the compiler can work around it

But with more complex types like complex, vectors, nominated structs, or in C++ classes with operator++, this can be outside the compiler's reach, and you might be spending for nothing

Put yourself in the habit of pre-incrementing.  There are times that you actually need postincrement, but they're rare, and preincrement is always a win or a tie.

**Comment by ellowrath** [comment]
Cool.  I was not aware of the temporaries detail. Noted and changed.
