### ISSUE TITLE
returning bool from everything

### ISSUE THREAD

**Issue by StoneCypher** [ellowrath/ClangMan#8]
Why are you returning bool from everything?

```c
static bool print_welcome_message() {
    printf("%s\n", WELCOME);
    return true;
}
```

lol.  what?

Is.  Is this being checked for success somewhere?  Does a failure condition exist?  Is this ... is this part of a comparator set?

When people see a return value, it implies there's some reason for the return value.  Unless you're actually checking for success somewhere, this ought to return `void`.

**Comment by ellowrath** [comment]
I was doing some checking at one point. The numerous print functions were to facilitate that. I'm rethinking those, based on your comments, so much of this will probably disappear with those.
